FROM python:3.12.0-slim

RUN apt-get update && apt-get install -y netcat-traditional

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

COPY . /app/

EXPOSE 8080

# CMD ["gunicorn", "app:app", "-b", "0.0.0.0:5000"]
CMD python app.py
