"""Add balance_sheet_json attribute to LoanApplication model

Revision ID: 1d42aa9b0428
Revises: 76eaf25be1f4
Create Date: 2023-11-29 14:01:45.502276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d42aa9b0428'
down_revision = '76eaf25be1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_sheet_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_column('balance_sheet_json')

    # ### end Alembic commands ###
