"""Add preassessed_loan_percentage attribute to LoanApplication model

Revision ID: 3aeb84623ccf
Revises: 1d42aa9b0428
Create Date: 2023-11-29 14:19:19.867793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aeb84623ccf'
down_revision = '1d42aa9b0428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preassesssed_loan_percentage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_column('preassesssed_loan_percentage')

    # ### end Alembic commands ###
