"""Add status attribute to LoanApplication model

Revision ID: 93e5d6015198
Revises: 3f1d3d327d5b
Create Date: 2023-11-27 20:17:40.274562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e5d6015198'
down_revision = '3f1d3d327d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
